### ISSUE TITLE
when using \ as folder separator, FileManager gets confused

### ISSUE THREAD

**Issue by aandreev0** [LemonJust/vodex#1]
If I use "backslash" to define data folder path, e.g.:

`spec['project_dir'] = "D:\data\20220215_h2b-gcamp\920_230mW_zScan_150umSpan_30Slices_3secVolume_bin2x_1/"`

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [13], in <cell line: 10>()
      7 spec['project_dir'] = "D:\calibration_data\220215_h2b-gcamp-tph2-trpv1\920_230mW_zScan_150umSpan_30Slices_3secVolume_bin2x_postCsn_10uM_1/"
      8 spec['frames_per_volume'] = 30
---> 10 experiment = vx.Experiment.from_spec(spec)
     11 experiment.summary()

File ~\Downloads\AnacondaApp\envs\vodex-test\lib\site-packages\vodex\core.py:680, in Experiment.from_spec(cls, spec)
    660 """
    661 Create experiment object from the specification dictionary.
    662 Necessary fields:
   (...)
    676 :type spec: dict of str: many things ...
    677 """
    679 cycle = Cycle(spec['conditions'], spec['timing'])
--> 680 frame_manager = FrameManager(FileManager(spec['project_dir']))
    682 if 'first_good_frame' in spec:
    683     volume_manager = VolumeManager(spec['frames_per_volume'], frame_manager, fgf=spec['first_good_frame'])

File ~\Downloads\AnacondaApp\envs\vodex-test\lib\site-packages\vodex\core.py:298, in FrameManager.__init__(self, file_manager, n_frames, frame_size, frame_to_file)
    295     self.n_frames = n_frames
    297 if frame_size is None:
--> 298     self.frame_size = self.get_frame_size()
    299 else:
    300     self.frame_size = frame_size

File ~\Downloads\AnacondaApp\envs\vodex-test\lib\site-packages\vodex\core.py:351, in FrameManager.get_frame_size(self)
    345 """
    346 Gets frame size.
    347 
    348 :return: height and width of an individual frame in pixels
    349 """
    350 # initialise tif file and open the stack
--> 351 tif_file = self.file_manager.tif_files[0]
    352 stack = TiffFile(tif_file, _multifile=False)
    353 page = stack.pages.get(0)

IndexError: list index out of range`

**Comment by LemonJust** [comment]
This is expected behavior; you need to provide a valid path. 
In Python, ```\``` in strings is used to escape characters. If you want a backslash in your string, use ```\\```. 

There are three ways to get a valid path ( this is not vodex related but Python in general) :

- use ```\\``` instead of ```\``` : ```"D:\\calibration_data\\...\\920_230mW_zScan_150umSpan_30Slices_3secVolume_bin2x_postCsn_10uM_1\\"``` 
- use ```/``` instead of ```\``` : ```"D:/calibration_data/.../920_230mW_zScan_150umSpan_30Slices_3secVolume_bin2x_postCsn_10uM_1/" ```
- if absolutely set on a single``` \```, use r to indicate that you don't want your string changed in any way : ```r"D:\calibration_data\...\920_230mW_zScan_150umSpan_30Slices_3secVolume_bin2x_postCsn_10uM_1/" ```

**Comment by LemonJust** [comment]
I guess I should include a better error message in the next version :)
